# nginx compose file
#
# https://nginx.org/
# https://hub.docker.com/_/nginx
#
# Nginx (pronounced "engine-x") is an open source reverse proxy server
# for HTTP, HTTPS, SMTP, POP3, and IMAP protocols, as well as a load
# balancer, HTTP cache, and a web server (origin server). The nginx project
# started with a strong focus on high concurrency, high performance and low
# memory usage. It is licensed under the 2-clause BSD-like license and it runs
# on Linux, BSD variants, Mac OS X, Solaris, AIX, HP-UX, as well as on other
# *nix flavors. It also has a proof of concept port for Microsoft Windows.
#
# 20190205 - scottjl - first official file

version: '3.6'

volumes:
    nginx_data:
        driver: local
        name: nginx_data

networks:
    default:
        external:
            name: appstack

services:
    nginx:
        container_name: nginx
        restart: always
        volumes:
            - './config:/config'
        environment:
            - PGID=2001
            - PUID=2001
            - TZ=America/Chicago
        image: linuxserver/nginx
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
            - "traefik.docker.network=appstack"
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:${SERVER_HOST}"
            - "traefik.port=80"
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
